#!/usr/bin/env bash

set -e
# set -x

if test -d "$(pwd)/.git"; then
    if [[ -z "$SCHEME_LIVE_VENV" ]]; then
        export SCHEME_LIVE_VENV=yes
        export SCHEME_LIVE_PREFIX=$(pwd)/local
        export SCHEME_LIVE_CORE_COUNT=$(nproc --ignore=1)
        export PATH="$SCHEME_LIVE_PREFIX/bin:$HOME/.local/bin:$PATH"

        if [[ -z "$@" ]]; then
            echo "Entering scheme-live environment..."
            bash
        else
            exec $@
        fi
    else
        echo "You are already in a virtual environment!"
    fi
else
    echo "You need to run $0 from the root of the repository..."
    exit 1
fi
