(import (scheme base) (live identifier) (live test))

(test-begin "live/identifier")

(test-group "identifier-case-split"
  (test-equal '("command" "output" "to" "string")
    (identifier-case-split "command_output_to_string"))
  (test-equal '("command" "output" "to" "string")
    (identifier-case-split "command-output-to_string"))
  (test-equal '("A" "Single" "Line")
    (identifier-case-split "ASingleLine"))
  (test-equal '("PHP" "Mode")
    (identifier-case-split "PHPMode"))
  (test-equal '("Ends" "With" "PHP")
    (identifier-case-split "EndsWithPHP"))
  (test-equal '("PHP" "And" "XML" "Too")
    (identifier-case-split "PHPAndXMLToo"))
  (test-equal '("php" "And" "Xml" "Too")
    (identifier-case-split "phpAndXmlToo"))
  (test-equal '("PH" "Pand" "XM" "Ltoo")
    ;; This one does not have the expected split.
    (identifier-case-split "PHPandXMLtoo"))
  (test-equal '("list" "take" "right")
    (identifier-case-split "list-take-right"))
  (test-equal '("list" "null" "?")
    (identifier-case-split "list-null?"))
  (test-equal '("string" "=" "?")
    (identifier-case-split "string=?"))
  (test-equal '("string" "ci" "<=" "?")
    (identifier-case-split "string-ci<=?"))
  (test-equal '("what" "happened" "?" "!")
    (identifier-case-split "what-happened?!")))

(test-end)
