(define (identifier-case-split str)
  (define (char-alphanumeric? char)
    (or (char-alphabetic? char) (char-numeric? char)))
  (define (split-off run runs)
    (if (null? run) runs (cons (list->string (reverse run)) runs)))
  (let loop ((runs '()) (run '()) (chars (string->list str)))
    (if (null? chars) (reverse (split-off run runs))
        (let ((char (car chars)))
          (cond ((or (char=? #\- char) (char=? #\_ char))
                 (loop (split-off run runs) '() (cdr chars)))
                ((or (char=? #\! char) (char=? #\? char))
                 (loop (cons (string char) (split-off run runs))
                       '() (cdr chars)))
                ((and (not (null? run))
                      (or (and (char-upper-case? char)
                               (not (char-upper-case? (car run))))
                          (not (eqv? (char-alphanumeric? char)
                                     (char-alphanumeric? (car run))))))
                 (loop (split-off run runs) (list char) (cdr chars)))
                ((and (not (char-upper-case? char))
                      (not (null? run))
                      (not (null? (cdr run)))
                      (char-upper-case? (car run))
                      (char-upper-case? (cadr run)))
                 (loop (split-off (cdr run) runs)
                       (list char (car run))
                       (cdr chars)))
                (else
                 (loop runs (cons char run) (cdr chars))))))))
