(define-library (twinjo binary write)
  (export twinjo-binary-write)
  (import (scheme base)
          (scheme char)
          (scheme write)
          (live bitwise)
          (live fixnum)
          (live hash-table))
  (include "write.scm"))
