name: Continuation Integration

on:
    push:

jobs:
    checks:
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          include:
            - IMPLEMENTATION: chez
            - IMPLEMENTATION: chibi
            - IMPLEMENTATION: chicken
            # - IMPLEMENTATION: cyclone
            - IMPLEMENTATION: gambit
            - IMPLEMENTATION: gauche
            - IMPLEMENTATION: gerbil
            - IMPLEMENTATION: guile
            - IMPLEMENTATION: loko
            - IMPLEMENTATION: mit
            - IMPLEMENTATION: racket
            - IMPLEMENTATION: sagittarius
      steps:
        - uses: actions/checkout@v2
        - name: host setup
          run: sudo make prepare-debian
        - name: install
          run: sudo ./venv scheme-live ${{ matrix.IMPLEMENTATION }} install
        - name: check
          run: sudo ./venv scheme-live ${{ matrix.IMPLEMENTATION }} check
