name: Continuation Integration

on:
    push:

jobs:
    checks:
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          include:
            - IMPLEMENTATION: chez
            - IMPLEMENTATION: chibi
            - IMPLEMENTATION: chicken
            - IMPLEMENTATION: cyclone
            - IMPLEMENTATION: gambit
            - IMPLEMENTATION: gauche
            - IMPLEMENTATION: gerbil
            - IMPLEMENTATION: guile
            - IMPLEMENTATION: loko
            - IMPLEMENTATION: mit
            - IMPLEMENTATION: racket
            - IMPLEMENTATION: sagittarius
      steps:
        - uses: actions/checkout@v2
        - name: check
          run: docker run --volume $(pwd):/live --interactive --rm ghcr.io/scheme-live/schemers:latest bash -c 'cp /live/local/shell-subcommand.sh . && cd /live && SCHEME_LIVE_PREFIX=/ PATH=/opt/live/${{ matrix.implementation }}/bin:/live/local/bin:/usr/bin/:/bin USER=github scheme-live ${{ matrix.implementation }} check'
